# ============================================================
# IDAM — Intelligent Automated Retail Store Backend
# app/api/llm.py
#
# PURPOSE:
#   FastAPI router for all LLM endpoints.
#   Routes are intentionally thin — HTTP concerns only.
#   All business logic lives in llm_service.py.
#
# ENDPOINTS:
#   POST /llm/query     — Phase 6: LLM-only query
#   POST /llm/rag-query — Phase 7: RAG-enriched query (semantic search + LLM)
#
# FUTURE ENDPOINTS (Phase 8+):
#   POST /chat/message  — Stateful chat with conversation memory
# ============================================================

import logging

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.database.connection import get_db
from app.schemas.llm import (
    LLMQueryRequest,
    LLMQueryResponse,
    RAGQueryRequest,
    RAGQueryResponse,
    LLMErrorResponse,
)
from app.services.llm_service import handle_query, handle_rag_query

logger = logging.getLogger(__name__)

router = APIRouter()


# ── POST /llm/query (Phase 6) ─────────────────────────────────

@router.post(
    "/query",
    response_model=LLMQueryResponse,
    summary="Send a natural-language query to the LLM (no catalog lookup)",
    description=(
        "Accepts a natural-language product query and returns a conversational response "
        "generated by the configured LLM (default: Groq Llama 3.3 70B, "
        "with automatic fallback to Google Gemini). "
        "Responses are based on the LLM's general knowledge only — "
        "no catalog retrieval is performed. Use /llm/rag-query for catalog-grounded answers."
    ),
    responses={
        200: {"description": "LLM response generated successfully",    "model": LLMQueryResponse},
        401: {"description": "Invalid API key",                        "model": LLMErrorResponse},
        502: {"description": "LLM provider unavailable or empty response", "model": LLMErrorResponse},
        504: {"description": "LLM request timed out",                  "model": LLMErrorResponse},
        500: {"description": "Internal server error",                  "model": LLMErrorResponse},
    },
)
def query_llm(request: LLMQueryRequest):
    """
    Query the LLM with a natural-language product question.

    **Powered by:** Groq (Llama 3.3 70B) with automatic fallback to Google Gemini.

    **This endpoint does NOT use the product catalog.** For catalog-grounded
    answers, use `POST /llm/rag-query` instead.

    **Response fields:**
    - `response` — The LLM's conversational answer
    - `provider` — Which LLM served the request (`"Groq"` or `"Gemini"`)
    """
    logger.info(f"[LLM API] POST /llm/query | Query length: {len(request.query)} chars")
    return handle_query(query=request.query)


# ── POST /llm/rag-query (Phase 7) ────────────────────────────

@router.post(
    "/rag-query",
    response_model=RAGQueryResponse,
    summary="RAG-enriched query — semantic search + LLM answer",
    description=(
        "Retrieves relevant products from the catalog using semantic search (ChromaDB), "
        "injects them into the LLM context, and returns a response grounded in real catalog data. "
        "The response includes the LLM answer AND the list of products that were shown to the LLM, "
        "so the frontend can render product cards alongside the AI response. "
        "If no matching products are found, the LLM falls back to general knowledge and "
        "rag_used is set to false."
    ),
    responses={
        200: {"description": "RAG response generated successfully",    "model": RAGQueryResponse},
        401: {"description": "Invalid API key",                        "model": LLMErrorResponse},
        502: {"description": "LLM provider unavailable or empty response", "model": LLMErrorResponse},
        504: {"description": "LLM request timed out",                  "model": LLMErrorResponse},
        500: {"description": "Internal server error",                  "model": LLMErrorResponse},
    },
)
def rag_query(
    request: RAGQueryRequest,
    db: Session = Depends(get_db),
):
    """
    Query the LLM with real product catalog context (RAG).

    **How it works:**
    1. Your query is embedded and searched against the product vector store (ChromaDB)
    2. The top matching products are retrieved and formatted as context
    3. Customer reviews are fetched for the top products (if available)
    4. The full context is injected into the LLM system prompt
    5. The LLM generates a response grounded in real catalog data

    **Example queries:**
    - `"I need a laptop for machine learning"` → retrieves laptops with AI/ML tags
    - `"Best wireless headphones with noise cancellation"` → retrieves ANC headphones
    - `"Budget smartphone under ₹25,000"` → retrieves affordable phones

    **Response fields:**
    - `response` — LLM's answer, referencing real products by name and price
    - `provider` — Which LLM served the request
    - `rag_used` — `true` if catalog products were injected; `false` if no matches found
    - `products_retrieved` — Number of products retrieved from ChromaDB
    - `products` — The retrieved products (for rendering product cards in the UI)

    **Graceful fallback:**
    If no products match the query, the endpoint does not fail — the LLM answers
    from general knowledge and `rag_used` is set to `false`.
    """
    logger.info(
        f"[LLM API] POST /llm/rag-query | Query: '{request.query[:60]}' | "
        f"top_k={request.top_k} | min_score={request.min_score}"
    )
    return handle_rag_query(
        query     = request.query,
        db        = db,
        top_k     = request.top_k,
        min_score = request.min_score,
    )
